<a href="https://colab.research.google.com/github/Sangeetha-122/projects-in-ML/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df =pd.read_csv(r'/content/sample_data/california_housing_test.csv')

# **INSPECT THE DATA**

In [6]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [7]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [10]:
df.shape

(3000, 9)

In [11]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

# **DATA SELECTION**

In [16]:
#ROW  and columns  selection
#to retrive with names row names,columns name
df.loc[0:6,"longitude":"latitude"]

   longitude  latitude
0    -122.05     37.37
1    -118.30     34.26
2    -117.81     33.78
3    -118.36     33.82
4    -119.67     36.33
5    -119.56     36.51
6    -121.43     38.63

In [18]:
#to retrive with indexes row index,column index it has -ve 1
df.iloc[0:2,0:2]

   longitude  latitude
0    -122.05     37.37
1    -118.30     34.26

# ** HANDELing null values**

In [19]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
#remove rows
#na means null values
df.dropna()
#fill the rows
#it fill with 0
df.fillna(0)

# **DATA TYPE CONVERSION**

In [20]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [28]:
df["total_rooms"]= df["total_rooms"].astype('int')

In [29]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241,244.0,850.0,237.0,2.9375,81700.0

# **REMOVE DUPLICATE ROWS**

In [ ]:
df.drop_duplicates()

# **DATA TRANSFORMATION AND ANALYSIS**

# SORTING DATA

In [30]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
df.sort_values(by ='"total_rooms')